language: node_js
node_js:
  - 12
before_install: cd packages/greenhouse
script: build-storybook -c .storybook -o .out
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: packages/greenhouse/.out
  on:
    branch: master
