name: Greenhouse

on:
  push:
    paths:
    - 'packages/greenhouse/**'
    - '.github/workflows/greenhouse.yml'

jobs:   
#   storybook:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 12
#     - name: build storybook
#       working-directory: packages/greenhouse
#       run: |
#         npm ci
#         npm run storybook:build
#     - name: deploy to pages
#       uses: JamesIves/github-pages-deploy-action@master
#       env:
#         ACCESS_TOKEN: ${{ secrets.GITHUB_PAGES_TOKEN }}
#         BASE_BRANCH: master
#         BRANCH: gh-pages
#         FOLDER: packages/greenhouse/.out
  
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: get version numbers
        env:
          PACKAGE_VERSION: ${{ node -p -e "require('./packages/greenhouse/package.json').version" }}
          PUBLISHED_VERSION: ${{ npm show @sunflower-lab/greenhouse version }}
        run: echo $PACKAGE_VERSION $PUBLISHED_VERSION
      - name: publish to npm
        if: $PACKAGE_VERSION != $PUBLISHED_VERSION
        working-directory: packages/greenhouse
        run: |
          npm ci
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
